// Reviewed against the linked primary sources on 2026-09-27.
// These are editable, unsent self-advocacy templates. Source freshness is applied
// by the shared registry; a route is a question path, never an eligibility ruling.
export const insuranceSources = [
  { id:'insurance-wa-correction', title:'How to appeal a health insurance denial', publisher:'Washington Office of the Insurance Commissioner', url:'https://www.insurance.wa.gov/insurance-resources/health-insurance/appealing-health-insurance-denial/how-appeal-health-insurance-denial', applicability:'Washington consumer guidance. Processing-versus-coverage distinction is useful elsewhere; state appeal rights must be verified.', summary:'Separates claim-processing correction from a request to reverse a coverage decision.' },
  { id:'insurance-cms-eob', title:'How to read a health insurance explanation of benefits', publisher:'CMS', url:'https://www.cms.gov/initiatives/your-patient-rights/medical-bill-rights/get-help/medical-bill-guides-resources/how-read-health-insurance-explanation-benefits', applicability:'Consumer explanation of EOB fields; the actual plan and current claim determine responsibility.', summary:'An EOB describes claim processing; it is not a payment demand.' },
  { id:'insurance-cms-cost-sharing', title:'Health insurance terms you should know', publisher:'CMS', url:'https://www.cms.gov/initiatives/your-patient-rights/medical-bill-rights/get-help/medical-bill-guides-resources/health-insurance-terms-you-should-know', applicability:'General insurance terminology, with covered-service and network conditions.', summary:'Allowed charges, plan payment, deductibles, coinsurance and patient responsibility are different amounts.' },
  { id:'insurance-cms-network-bill', title:'Action plan: bill with an in-network provider', publisher:'CMS', url:'https://www.cms.gov/initiatives/your-patient-rights/medical-bill-rights/get-help/find-action-plan-your-medical-bill/action-plan-bill-network-provider', applicability:'Insured patients comparing a bill with the corresponding in-network EOB.', summary:'Compare the bill with the EOB; request provider correction for discrepancies or a plan appeal for an incorrect determination.' },
  { id:'insurance-uhc-2026-guide', title:'2026 UnitedHealthcare provider administrative guide', publisher:'UnitedHealthcare', url:'https://www.uhcprovider.com/content/dam/provider/docs/public/admin-guides/2026-UHC-Administrative-Guide.pdf', applicability:'Named UnitedHealthcare products, agreements and supplements only; not a universal patient right or filing deadline.', summary:'Provider filing rules depend on agreements and state requirements; accepted-claim evidence matters. Peer discussions and formal appeals are distinct.' },
  { id:'insurance-cms-directory', title:'ACA and Consolidated Appropriations Act implementation FAQs, Part 49', publisher:'U.S. Departments of Labor, HHS and Treasury', url:'https://www.cms.gov/cciio/resources/fact-sheets-and-faqs/downloads/faqs-part-49.pdf', applicability:'Provider-directory reliance protections for applicable group and individual coverage; verify plan, timing and evidence.', summary:'Inaccurate network information supplied by a plan can affect the permitted cost sharing and accumulator treatment.', effectiveFrom:'2022-01-01' },
  { id:'insurance-healthcare-internal', title:'Internal health plan appeals', publisher:'HealthCare.gov', url:'https://www.healthcare.gov/appeal-insurance-company-decision/internal-appeals/', applicability:'Applicable private health coverage; separate Medicare, Medicaid and other program procedures must be used.', summary:'A formal appeal asks the plan to reconsider a denial; evidence, submission proof and the correct appeal deadline matter.' },
  { id:'insurance-healthcare-external', title:'External review of health plan decisions', publisher:'HealthCare.gov', url:'https://www.healthcare.gov/appeal-insurance-company-decision/external-review/', applicability:'Eligible adverse decisions under applicable state or federal review processes; not every billing dispute qualifies.', summary:'Eligible medical-judgment and other specified denials may receive independent review using the process identified in the notice.' },
  { id:'insurance-healthcare-preauth', title:'Preauthorization', publisher:'HealthCare.gov', url:'https://www.healthcare.gov/glossary/preauthorization/', applicability:'General private insurance definition; coverage and payment conditions remain plan-specific.', summary:'Prior authorization by itself does not guarantee payment.' },
  { id:'insurance-naic-denials', title:'How to appeal a denied health care claim', publisher:'National Association of Insurance Commissioners', url:'https://content.naic.org/sites/default/files/inline-files/how-to-appeal-a-denied-claim.pdf', applicability:'General consumer claim-denial guidance; check the member notice and governing plan process.', summary:'Read the denial and policy, assemble supporting material, and follow the correct internal or external review path.' },
  { id:'insurance-dol-claim-file', title:'Filing a claim for health or disability benefits', publisher:'U.S. Department of Labor, EBSA', url:'https://www.dol.gov/node/63367', applicability:'ERISA-covered employee benefit plans; additional protections depend on plan and claim type.', summary:'Explains denial reasons, plan provisions, relevant records, benefit-claim procedures and review rights.' },
  { id:'insurance-dol-fiduciary', title:'Fiduciary responsibilities under a group health plan', publisher:'U.S. Department of Labor, EBSA', url:'https://www.dol.gov/node/63394', applicability:'ERISA group health plans; not every employer arrangement is covered.', summary:'Addresses claims administration, relevant claim records and clinical reasons supporting adverse decisions.' },
  { id:'insurance-dol-procedures', title:'Benefit claims procedure regulation FAQs', publisher:'U.S. Department of Labor, EBSA', url:'https://www.dol.gov/agencies/ebsa/about-ebsa/our-activities/resource-center/faqs/benefit-claims-procedure-regulation', applicability:'ERISA procedure guidance; additional ACA standards and current plan-specific rules also matter.', summary:'Distinguishes informal inquiries from claims filed through reasonable procedures and explains relevant claim information.' },
  { id:'insurance-dol-recordings', title:'Information letter on relevant claim recordings', publisher:'U.S. Department of Labor, EBSA', url:'https://www.dol.gov/agencies/ebsa/about-ebsa/our-activities/resource-center/information-letters/06-14-2021', applicability:'ERISA claim-file disclosure where an existing recording or transcript is relevant to the benefit determination.', summary:'A retained call recording may be relevant claim material even when created for quality assurance.' },
  { id:'insurance-wa-jurisdiction', title:'Who to contact about an employer health plan', publisher:'Washington Office of the Insurance Commissioner', url:'https://www.insurance.wa.gov/insurance-resources/health-insurance/health-insurance-coverage/who-contact-issues-your-employer-health-plan', applicability:'Washington routing examples; use the regulator for the actual plan and jurisdiction elsewhere.', summary:'Fully insured, self-funded private, government and religious-employer arrangements require different escalation paths.' },
  { id:'insurance-cms-government', title:'Self-funded non-federal governmental plans', publisher:'CMS', url:'https://www.cms.gov/marketplace/private-health-insurance/self-funded-non-federal-governmental-plans', applicability:'State and local government health plans subject to applicable Public Health Service Act provisions.', summary:'CMS has a distinct enforcement role for non-federal governmental plans; private-employer ERISA routing cannot simply be assumed.' }
];

export const insuranceRoutes = [
  {
    id:'insurance-processing-correction', title:'Get a claim processing problem corrected', category:'coverage',
    summary:'Find the specific data or payment mismatch and the team that can fix it.',
    pattern:'A rejection, missing record, unposted payment or deductible calculation can resemble a coverage denial.',
    appliesWhen:'Insurance is involved and the claim status or reason for nonpayment is unclear.',
    verify:['Is this a provider bill, an EOB, or a written denial?', 'Was the claim accepted, returned, awaiting information, partly paid, or denied?', 'Do the latest EOB and bill describe the same services?', 'Which field, record or cost-sharing amount is disputed?'],
    firstMove:{title:'Ask for a specific correction path',steps:['Get the current EOB and itemized provider ledger.', 'Ask the payer to classify the issue and identify the exact missing or incorrect information.', 'Ask the provider to verify the original record and submit a supported correction if needed.', 'Record the formal appeal route and deadline separately.'],draft:'Please explain the current claim status and the precise reason for nonpayment. Is this a processing correction or an adverse coverage decision? Identify what must change, who must submit it, and how I will confirm receipt. Please also identify my separate appeal procedure and deadline.'},
    responses:{
      no_reply:{title:'Confirm receipt and preserve the appeal path',steps:['Request written receipt and a follow-up date from the responsible team.', 'If there is a denial, follow its formal appeal instructions before the stated deadline.'],draft:'I have not received confirmation of this correction request. Please confirm receipt and the next step. I also need the instructions for a formal member appeal; please do not treat this inquiry as a substitute.'},
      more_info:{title:'Match the request to the actual missing evidence',steps:['Ask exactly which record or field is missing.', 'Have its owner send it through the payer’s verified secure channel.', 'Keep receipt evidence locally.'],draft:'Please list the missing information and explain which unresolved issue it addresses. Confirm the secure submission method and whether a separate appeal filing is still required.'},
      denied:{title:'Switch to a documented appeal if coverage remains disputed',steps:['Get the written rationale and applicable plan provision.', 'Choose the denial-evidence route; retain proof of any formal filing.'],draft:'The correction did not resolve this claim. Please provide the written determination, the policy provision applied and the remaining member appeal options.'}
    },
    watchouts:['An EOB is not a bill. Zero plan payment can reflect a deductible.', 'Ask the provider to correct factual errors; do not invent diagnoses or change accurate codes to obtain coverage.', 'A call or corrected claim does not automatically extend a member appeal deadline or suspend billing.'],
    sourceIds:['insurance-wa-correction','insurance-cms-eob','insurance-cms-cost-sharing','insurance-naic-denials','insurance-dol-procedures'],
    triggers:{documentTypes:['bill','eob','denial'],goals:['understand','check','appeal'],coverage:['private']}
  },
  {
    id:'insurance-network-liability', title:'Check who owes a disputed network charge', category:'coverage',
    summary:'Challenge an unexplained transfer of provider or insurer responsibility to you.',
    pattern:'A bill above the EOB, late provider filing or an authorization dispute needs a responsibility check.',
    appliesWhen:'The provider was believed to be in-network and a bill conflicts with the EOB or an administrative denial.',
    verify:['Was this provider and location in-network for the service?', 'Is the EOB final and matched to this bill?', 'What patient responsibility does it actually show?', 'Is the reason late filing, missing authorization, a contract adjustment or a coverage exclusion?', 'Is there saved plan-directory or network-confirmation evidence?'],
    firstMove:{title:'Ask the plan to explain member liability',steps:['Compare the current EOB with payments and adjustments on the provider ledger.', 'Ask whether the disputed amount is patient cost sharing or provider responsibility.', 'For late filing, ask the provider for accepted-claim evidence and its contract-specific correction path.', 'Request a written billing hold; keep the appeal deadline independently.'],draft:'Please reconcile this bill with the current EOB. If the issue is provider filing or authorization compliance, identify the applicable provision that permits charging me. Please have the plan’s provider-relations team clarify responsibility and issue corrected statements if appropriate.'},
    responses:{
      no_reply:{title:'Escalate the responsibility question',steps:['Request a billing supervisor and plan provider-relations review.', 'Preserve the member appeal and any collection-response deadlines.'],draft:'Please route this unresolved patient-responsibility question to a billing supervisor and the plan’s provider-relations team. Confirm any billing hold in writing; I have not assumed one exists.'},
      more_info:{title:'Supply the matching evidence',steps:['Send only the relevant EOB, ledger or network confirmation through verified channels.', 'Ask which item supports charging the disputed amount.'],draft:'Please identify the precise mismatch and the evidence you need. If your network information was incorrect, explain the applicable cost-sharing protection and how to request reprocessing.'},
      denied:{title:'Get the contractual reason before the next escalation',steps:['Request the written basis and applicable member appeal path.', 'If needed, seek help from the regulator responsible for this plan.'],draft:'Please provide the written basis for assigning this amount to me, including the controlling plan or contract provision and the next review process. A general statement that insurance did not pay does not resolve the responsibility question.'}
    },
    watchouts:['Administrative denial does not prove that a debt is invalid; coverage, agreements and law matter.', 'Provider filing limits and member appeal limits are different.', 'Ask for written correction or refund confirmation; do not count an unresolved amount as savings.'],
    sourceIds:['insurance-cms-network-bill','insurance-cms-cost-sharing','insurance-uhc-2026-guide','insurance-cms-directory'],
    triggers:{documentTypes:['bill','eob','denial'],goals:['understand','check','afford','appeal'],coverage:['private']}
  },
  {
    id:'insurance-evidence-appeal', title:'Build an appeal around the actual denial reason', category:'coverage',
    summary:'Connect the plan’s stated requirement to the evidence that answers it.',
    pattern:'A generic complaint may leave the actual coverage or clinical criterion unanswered.',
    appliesWhen:'There is a written private-plan denial that the member disputes.',
    verify:['What is the written reason and policy provision?', 'Is this missing evidence, medical necessity, an exclusion or another issue?', 'Which records and criteria did the reviewer use?', 'Has a clinician confirmed urgency or offered supporting evidence?', 'What appeal level, channel and deadline does the notice specify?'],
    firstMove:{title:'Request the reasoning and assemble a focused appeal',steps:['Obtain the denial, governing plan terms and relevant claim file; ask about free access rights.', 'Where ERISA applies, request relevant retained call recordings or transcripts as part of that file.', 'Ask the clinician to address the specific criterion using existing records when appropriate.', 'Submit the member appeal through the required channel and retain receipt proof.', 'Ask whether any peer discussion changes the decision or counts as an appeal.'],draft:'I am appealing the decision described in the attached notice. My requested correction is [state it]. The supporting evidence is [list the records]. Please explain [the disputed criterion] and provide the relevant claim file. Confirm receipt as a formal member appeal and identify any missing filing requirement.'},
    responses:{
      no_reply:{title:'Check the formal appeal was received',steps:['Distinguish a records request from an accepted appeal.', 'Seek plan-administrator or regulator help with an unresolved procedural delay.'],draft:'Please confirm whether my submission is recorded as a formal appeal, its received date and the response deadline. If it is incomplete, specify the missing requirement promptly.'},
      more_info:{title:'Answer each stated gap',steps:['Match each requested item to an actual record or clinician response.', 'Confirm the supplement arrived and whether deadlines changed in writing.'],draft:'Please identify each remaining evidentiary gap and the criterion it relates to. I am requesting a targeted response from my clinician. Confirm how supplemental material will be included in the review.'},
      denied:{title:'Check remaining review rights',steps:['Obtain the final rationale and notice of remaining internal or external review.', 'Check eligibility and the applicable filing deadline before requesting independent review.'],draft:'Please provide the final reason, any new evidence or rationale relied on, and the instructions for the next available review. Identify whether independent external review is available for this decision.'}
    },
    watchouts:['Do not let a records request delay a required appeal; clinicians must support clinical arguments and urgency.', 'Prior authorization alone is not a payment guarantee.', 'A peer discussion, records request or phone call may not satisfy formal appeal requirements.', 'External review does not cover every disagreement.'],
    sourceIds:['insurance-dol-claim-file','insurance-dol-fiduciary','insurance-dol-recordings','insurance-healthcare-internal','insurance-healthcare-external','insurance-healthcare-preauth','insurance-naic-denials','insurance-uhc-2026-guide'],
    triggers:{documentTypes:['denial','eob','bill'],goals:['appeal','check','understand'],coverage:['private'],anyOf:[{documentType:'denial'},{claimStatus:'denied'},{goal:'appeal'}]}
  },
  {
    id:'insurance-plan-escalation', title:'Find the authority responsible for your plan', category:'coverage',
    summary:'Confirm funding and plan type before escalating an unresolved denial.',
    pattern:'The company on an insurance card may administer claims without funding them.',
    appliesWhen:'An employer-plan dispute is unresolved or its review process is unclear.',
    verify:['Is the arrangement fully insured, self-funded, mixed or unknown?', 'Is the sponsor private, government or religious?', 'Who is the named plan administrator?', 'Which plan documents and claims procedures are available?', 'What formal appeals have been filed or decided?'],
    firstMove:{title:'Get the plan’s identity and review map',steps:['Request the current plan description, controlling coverage terms and claims procedures.', 'Ask the administrator to confirm funding, applicable protections and the next review body.', 'Use state insurance assistance for an insured-policy issue, EBSA for applicable private ERISA issues, or the appropriate government-plan process.', 'Keep formal filings active while seeking help.'],draft:'Please identify the named plan administrator, whether this coverage is insured or self-funded, and whether ERISA applies. Please provide the governing benefit and claims documents and identify the proper appeal and external-review process. I only need plan-level information from my employer’s benefits contact.'},
    responses:{
      no_reply:{title:'Ask the appropriate assistance office to help identify the plan',steps:['Use plan documents and the denial notice to request routing help.', 'Keep proof of prior requests and preserve the member filing deadline.'],draft:'I need help identifying the correct authority and review process. The administrator has not answered my plan-level request. Please explain your jurisdiction and any additional routing information needed.'},
      more_info:{title:'Share a focused procedural record',steps:['Provide the denial, plan details and appeal history only through the recipient’s secure channel.', 'Keep medical narratives out of ordinary HR correspondence.'],draft:'Please identify the documents needed to determine your authority or review this procedural issue. I will submit any necessary claim material directly through the designated secure process.'},
      denied:{title:'Request the next available route',steps:['Ask whether this is a jurisdiction decision, a complaint closure or a benefit determination.', 'Follow the appropriate remaining appeal, external review or legal-assistance path.'],draft:'Please explain whether this response decides benefits or only closes your assistance review. Identify any remaining appeal, independent review or other process and its filing requirements.'}
    },
    watchouts:['Government and church arrangements are not automatically ERISA plans.', 'A regulator complaint is not automatically a formal benefit appeal.', 'A plan-specific exception can be requested, but approval is discretionary unless an applicable right is established.', 'GoldRock does not send case details to an employer; choosing to contact a plan fiduciary can disclose details to that recipient.'],
    sourceIds:['insurance-wa-jurisdiction','insurance-cms-government','insurance-dol-claim-file','insurance-dol-fiduciary','insurance-healthcare-external'],
    triggers:{documentTypes:['bill','eob','denial','estimate'],goals:['understand','check','appeal','plan'],coverage:['private']}
  }
];
