/** Reviewed public education. These are preparation routes, not price or coverage decisions. */
export const priceSources = [
  { id:'cms-hospital-price-consumers', title:'Use hospital price transparency', url:'https://www.cms.gov/priorities/key-initiatives/hospital-price-transparency/consumers', publisher:'CMS', applicability:'Published hospital standard charges and scheduled services; confirm the matching service and setting.', summary:'Public cash and negotiated charges are useful comparison inputs; request an estimate for the actual care.' },
  { id:'cms-price-faq', title:'Hospital price transparency: limits of standard charges', url:'https://www.cms.gov/files/document/hospital-price-transparency-frequently-asked-questions.pdf', publisher:'CMS', applicability:'Hospital standard-charge information; this does not determine a particular patient’s responsibility.', summary:'A standard charge is neither an individual out-of-pocket obligation nor a guaranteed price.' },
  { id:'cms-provider-bill-conversation', title:'Discuss a medical bill with your provider', url:'https://www.cms.gov/initiatives/your-patient-rights/medical-bill-rights/get-help/medical-bill-guides-resources/talk-your-provider-about-your-medical-bill', publisher:'CMS', applicability:'Provider billing discussion and requested reductions; no guaranteed discount or payment hold.', summary:'Use specific charges and written questions to discuss an unexplained or unaffordable bill.' },
];
export const priceRoutes = [{
  id:'compare-real-cost', title:'A lower cash price caught my eye', category:'before-care',
  summary:'Compare the same included services and your full cost before choosing a payment route.',
  pattern:'A headline price may omit another biller or differ from the amount you would owe using insurance.',
  appliesWhen:'For planned, non-urgent care or a question about a listed price. A comparison does not establish that an existing bill is wrong.',
  verify:['Same service, code, setting and included billers?', 'Does the quote use insurance or require self-pay?', 'If you can use insurance, what does the plan estimate you would owe?', 'Which services, fees or complications are excluded?'],
  firstMove:{title:'Compare like-for-like written estimates',steps:['Ask the provider to itemize the offer and included services.', 'If using insurance, ask your plan for your estimated share and how choosing self-pay affects deductible or out-of-pocket credit.', 'If uninsured or not using insurance, ask about a good faith estimate and clarify separate providers’ charges.', 'Match services and exclusions before comparing the quoted totals.'],draft:'Please itemize the quoted services, separate billers and exclusions. If I can use insurance, I will compare the plan’s estimate and ask about deductible or out-of-pocket credit. If I will not use insurance, please explain the good faith estimate process and which separate providers I should contact.'},
  responses:{
    no_reply:{title:'Ask the right estimate team',steps:['Request the provider’s estimate or financial-counseling team.', 'Use the official published pricing page as a question, preserving its service description.'],draft:'I need clarification of the quoted services and my payment options. Please route this to the team that can provide a written estimate.'},
    more_info:{title:'Resolve the comparison gaps',steps:['List services included on one quote but missing from the other.', 'Ask the clinician or scheduler to confirm the planned service without changing care solely for price.'],draft:'These estimates appear to include different services. Please identify what is missing and which clinicians may bill separately.'},
    denied:{title:'Separate a refused discount from an error',steps:['Ask which term makes the advertised price inapplicable.', 'For an existing bill, consider assistance or an accuracy review separately.', 'For future care, discuss clinically appropriate alternatives with your clinician.'],draft:'Please explain which condition of the published price does not match my care. If a reduction is unavailable, please provide the assistance policy and direct payment-plan options.'},
  },
  watchouts:['Published standard charges do not automatically replace a bill.', 'Do not delay urgent care for price comparison.', 'An estimate and prior authorization do not guarantee coverage or a final price.'],
  sourceIds:['cms-hospital-price-consumers','cms-price-faq','cms-provider-bill-conversation','cms-price-transparency','healthcare-preauthorization','cms-gfe-dispute'],
  triggers:{documentTypes:['estimate'],goals:['plan'],coverage:['private','uninsured','self_pay']},
}];
