import { billingSources } from './billing-routes.js';
import { insuranceSources } from './insurance-routes.js';
import { priceSources } from './price-routes.js';
import { knowledgeSources } from './knowledge-concepts.js';
import { exceptionSources } from './knowledge-exceptions.js';
import { scenarioSources } from './scenario-playbooks.js';
import { countermeasureSources } from './knowledge-countermeasures.js';
/** Reviewed primary-source knowledge registry; this is curated research, not live retrieval. */
export const SOURCE_REVIEWED_AT = '2026-09-27T00:00:00.000Z';
export const SOURCE_EXPIRES_AT = '2026-12-27T00:00:00.000Z';
const entry = (id, title, url, publisher, applicability, summary, effectiveFrom = null) => Object.freeze({ id, title, url, publisher, jurisdiction: 'US', applicability, summary, reviewedAt: SOURCE_REVIEWED_AT, expiresAt: SOURCE_EXPIRES_AT, effectiveFrom, reviewMethod: 'Official source material reviewed (page, PDF or indexed excerpts); applicability still requires case facts.' });
export const sources = Object.freeze([
  ...[...billingSources,...insuranceSources,...priceSources,...knowledgeSources,...exceptionSources,...scenarioSources,...countermeasureSources].map(source => Object.freeze({...entry(source.id,source.title,source.url,source.publisher,source.applicability,source.summary,source.effectiveFrom ?? null),...(source.reviewedAt?{reviewedAt:source.reviewedAt}:{}),...(source.expiresAt?{expiresAt:source.expiresAt}:{}),...(source.reviewMethod?{reviewMethod:source.reviewMethod}:{})})),
  entry('cms-eob', 'EOB or medical bill: understand the difference', 'https://www.tdi.texas.gov/podcast/explanation-of-benefits-medical-bill-differences.html', 'Texas Department of Insurance', 'General document explanation; no state-specific remedy inferred.', 'An EOB explains claim processing and possible responsibility; it is not a demand for payment.'),
  entry('cms-medical-bill-rights', 'Know your medical bill rights', 'https://www.cms.gov/initiatives/your-patient-rights/medical-bill-rights/know-your-medical-bill-rights', 'CMS', 'Coverage and setting must be confirmed.', 'The correct consumer route depends on whether insurance was used and the type of care.'),
  entry('cms-no-surprises', 'Protection from unexpected out-of-network bills', 'https://www.cms.gov/initiatives/your-patient-rights/medical-bill-rights/know-your-medical-bill-rights', 'CMS', 'Qualifying private coverage; emergency, certain in-network facility services, air ambulance; confirm exceptions.', 'Federal protections can limit some out-of-network patient charges; ground ambulance generally needs another route.', '2022-01-01'),
  entry('cms-gfe-dispute', 'Dispute a bill above a good faith estimate', 'https://www.cms.gov/initiatives/your-patient-rights/medical-bill-rights/get-help/dispute-bill', 'CMS', 'Uninsured/self-pay; matching provider estimate and bill; qualifying timing and notice.', 'Check the $400 difference, 120-calendar-day initial bill window, advance estimate, care timing and self-pay conditions before filing.', '2022-01-01'),
  entry('healthcare-appeals', 'Internal health-plan appeals', 'https://www.healthcare.gov/appeal-insurance-company-decision/internal-appeals/', 'HealthCare.gov', 'Applicable health plans; actual notice and plan procedure control individual routing.', 'A denial can be reviewed through a documented appeal with relevant supporting records. Confirm the deadline in the notice.'),
  entry('healthcare-external-review', 'Independent external review', 'https://www.healthcare.gov/appeal-insurance-company-decision/external-review/', 'HealthCare.gov', 'Eligible denial types and applicable state/federal or plan review process; not every billing dispute.', 'The final denial and plan type identify the review route. Urgent situations may require an expedited process.'),
  entry('irs-financial-assistance', 'Hospital financial assistance policies', 'https://www.irs.gov/charities-non-profits/financial-assistance-policies-faps', 'IRS', 'Covered tax-exempt hospital facilities; exact policy, care and provider list must be checked.', 'Policies specify eligibility and application rules; a hospital policy may exclude separately billing providers.'),
  entry('irs-collections', 'Hospital billing and collection requirements', 'https://www.irs.gov/charities-non-profits/billing-and-collections-section-501r6', 'IRS', 'Section 501(r) hospital extraordinary collection actions; not a blanket hold on all bills.', 'Covered hospitals must make reasonable efforts to determine financial-assistance eligibility before extraordinary collection actions.'),
  entry('cfpb-medical-debt', 'When you cannot pay a medical bill', 'https://www.consumerfinance.gov/ask-cfpb/what-should-i-do-if-i-cant-pay-a-medical-bill-en-2125/', 'CFPB', 'General bill review, assistance and payment options; state/plan details may differ.', 'Review accuracy and assistance before choosing repayment or financing; ask for clear written terms.'),
  entry('medicare-appeals', 'Medicare appeals', 'https://www.medicare.gov/providers-services/claims-appeals-complaints/appeals', 'Medicare.gov', 'Original Medicare, Medicare health or drug plans each have their own appeal process.', 'Use the coverage-specific decision notice and next-level appeal instructions.'),
  entry('medicaid-appeals', 'Medicaid and CHIP state assistance', 'https://www.medicaid.gov/about-us/where-can-people-get-help-medicaid-chip', 'Medicaid.gov', 'State Medicaid agency and plan, confirmed from the member notice.', 'Contact the appropriate state agency for Medicaid coverage and claims assistance.'),
  entry('cms-price-transparency', 'Compare planned-care costs', 'https://www.cms.gov/priorities/healthplan-price-transparency/overview/consumers', 'CMS', 'Applicable plan comparison tools; estimates are not final responsibility.', 'Ask for an estimate reflecting the service, network and plan and identify separately billed care.'),
  entry('healthcare-preauthorization', 'What preauthorization means', 'https://www.healthcare.gov/glossary/preauthorization/', 'HealthCare.gov', 'Applicable plan authorization requirements.', 'Preauthorization does not guarantee that the plan pays all costs.'),
  entry('cfpb-collection-contact', 'Responding to a debt collector', 'https://www.consumerfinance.gov/ask-cfpb/what-should-i-do-when-a-debt-collector-contacts-me-en-1695/', 'CFPB', 'Debt collectors; establish identity and the debt before sharing financial information.', 'Request validation and keep records of your response. Do not ignore a court deadline.'),
  entry('cfpb-debt-validation', 'Debt validation information', 'https://www.consumerfinance.gov/ask-cfpb/what-information-does-a-debt-collector-have-to-give-me-about-the-debt-en-331/', 'CFPB', 'Applicable third-party debt collection; notice, dates and debt must be verified.', 'A timely written dispute can require a collector to pause collection of the disputed amount pending verification.'),
  entry('cfpb-medical-financing', 'Medical credit cards and payment plans', 'https://www.consumerfinance.gov/ask-cfpb/what-should-i-know-about-medical-credit-cards-and-payment-plans-for-medical-bills-en-1827/', 'CFPB', 'Actual financing agreement and provider options; no lender recommendation.', 'Review assistance, total cost and deferred-interest conditions before accepting medical financing.'),
  entry('cfpb-debt-legal-process', 'Debt collection and court process', 'https://www.consumerfinance.gov/consumer-tools/debt-collection/answers/key-terms/', 'CFPB', 'Applicable state law, court notice and debt type; individual legal help may be needed.', 'A collection letter is distinct from a lawsuit. Court deadlines and statutes of limitation require case-specific review.'),
]);
export const SOURCE_IDS = Object.freeze(sources.map(source => source.id));
export function getSource(id, { now = new Date() } = {}) {
  const source = sources.find(item => item.id === id);
  if (!source) return null;
  const time = new Date(now).getTime();
  return { ...source, current: Number.isFinite(time) && time >= Date.parse(source.reviewedAt) && time < Date.parse(source.expiresAt) };
}
export function getCurrentSources({ now = new Date() } = {}) { return sources.filter(source => getSource(source.id, { now }).current); }
