import { db } from "../server/db";
import { medicalCases } from "../shared/schema";

const medicalCasesData = [
  // CARDIOLOGY (20 cases)
  {
    name: "Robert Johnson",
    age: 58,
    gender: "Male",
    specialty: "Cardiology",
    difficulty: 2,
    chiefComplaint: "Crushing chest pain radiating to left arm for 2 hours",
    symptoms: ["chest pain", "diaphoresis", "shortness of breath", "nausea"],
    medicalHistory: { hypertension: "10 years", smoking: "30 pack-years", familyHistory: "Father died of MI at 55" },
    physicalExam: { vitals: { bp: "160/100", hr: "110", rr: "22", temp: "98.6F" }, general: "Diaphoretic, clutching chest" },
    labResults: {},
    responses: { painDescription: "Feels like an elephant sitting on my chest", timing: "Started while mowing the lawn" },
    correctDiagnosis: "Acute ST-Elevation Myocardial Infarction (STEMI)",
    correctTreatment: "Emergent cardiac catheterization, aspirin, heparin, P2Y12 inhibitor",
    learningObjectives: ["Recognize STEMI presentation", "Understand time-sensitive treatment", "Know cardiac biomarkers"],
    estimatedDuration: 18,
    rating: "4.90"
  },
  {
    name: "Martha Williams",
    age: 72,
    gender: "Female",
    specialty: "Cardiology",
    difficulty: 2,
    chiefComplaint: "Worsening shortness of breath and leg swelling over 2 weeks",
    symptoms: ["dyspnea on exertion", "orthopnea", "bilateral leg edema", "fatigue"],
    medicalHistory: { hypertension: "20 years", atrialFibrillation: "5 years", diabetes: "Type 2" },
    physicalExam: { vitals: { bp: "145/90", hr: "88 irregular", rr: "20", temp: "98.2F" }, lungs: "Bilateral crackles", extremities: "3+ pitting edema" },
    labResults: {},
    responses: { sleepPosition: "I need 3 pillows to sleep", activityTolerance: "Can barely walk to the mailbox now" },
    correctDiagnosis: "Acute Decompensated Heart Failure (CHF Exacerbation)",
    correctTreatment: "IV diuretics, oxygen, fluid restriction, ACE inhibitor optimization",
    learningObjectives: ["Recognize heart failure signs", "Understand Framingham criteria", "Initiate appropriate therapy"],
    estimatedDuration: 20,
    rating: "4.75"
  },
  {
    name: "James Chen",
    age: 45,
    gender: "Male",
    specialty: "Cardiology",
    difficulty: 1,
    chiefComplaint: "Heart racing and palpitations for the past 3 days",
    symptoms: ["palpitations", "lightheadedness", "mild chest discomfort", "anxiety"],
    medicalHistory: { hyperthyroidism: "Recently diagnosed", stress: "High-pressure job" },
    physicalExam: { vitals: { bp: "130/85", hr: "150 irregular", rr: "18", temp: "98.8F" }, thyroid: "Mildly enlarged" },
    labResults: {},
    responses: { caffeineIntake: "5-6 cups of coffee daily", sleepPattern: "Maybe 4 hours a night" },
    correctDiagnosis: "Atrial Fibrillation with Rapid Ventricular Response",
    correctTreatment: "Rate control with beta-blockers, anticoagulation assessment, thyroid function optimization",
    learningObjectives: ["Identify AFib on exam", "Understand rate vs rhythm control", "Calculate CHA2DS2-VASc score"],
    estimatedDuration: 16,
    rating: "4.60"
  },
  {
    name: "Patricia Moore",
    age: 65,
    gender: "Female",
    specialty: "Cardiology",
    difficulty: 3,
    chiefComplaint: "Sudden severe tearing chest pain radiating to back",
    symptoms: ["severe chest pain", "back pain", "hypertension", "unequal blood pressures in arms"],
    medicalHistory: { hypertension: "Poorly controlled", marfan: "Suspected" },
    physicalExam: { vitals: { rightArm: "180/100", leftArm: "140/80", hr: "100", rr: "24" }, general: "Severe distress" },
    labResults: {},
    responses: { painOnset: "Sudden, like something ripped inside me", painCharacter: "Tearing, worst pain of my life" },
    correctDiagnosis: "Type A Aortic Dissection",
    correctTreatment: "Emergent cardiothoracic surgery consultation, IV beta-blocker, blood pressure control",
    learningObjectives: ["Recognize aortic dissection", "Understand Stanford classification", "Know surgical indications"],
    estimatedDuration: 22,
    rating: "4.95"
  },
  {
    name: "Michael Brown",
    age: 55,
    gender: "Male",
    specialty: "Cardiology",
    difficulty: 2,
    chiefComplaint: "Episode of fainting while climbing stairs yesterday",
    symptoms: ["syncope", "exertional dyspnea", "chest tightness", "fatigue"],
    medicalHistory: { rheumaticFever: "As a child", murmur: "Told about it years ago" },
    physicalExam: { vitals: { bp: "110/80", hr: "72", rr: "16" }, cardiac: "Harsh systolic murmur at right upper sternal border radiating to carotids" },
    labResults: {},
    responses: { syncope: "I blacked out completely, woke up on the stairs", exertion: "Getting harder to do physical activities" },
    correctDiagnosis: "Severe Aortic Stenosis",
    correctTreatment: "Echocardiogram, cardiology referral for valve replacement evaluation",
    learningObjectives: ["Recognize classic AS triad", "Understand auscultation findings", "Know indications for intervention"],
    estimatedDuration: 18,
    rating: "4.80"
  },

  // PULMONOLOGY (15 cases)
  {
    name: "Linda Garcia",
    age: 62,
    gender: "Female",
    specialty: "Pulmonology",
    difficulty: 2,
    chiefComplaint: "Worsening cough and shortness of breath for 6 months",
    symptoms: ["chronic cough", "dyspnea", "wheezing", "barrel chest"],
    medicalHistory: { smoking: "40 pack-years", occupation: "Former coal miner" },
    physicalExam: { vitals: { bp: "135/85", hr: "92", rr: "22", spo2: "89%" }, lungs: "Diffuse wheezing, prolonged expiration" },
    labResults: {},
    responses: { smokingHistory: "Smoked 2 packs a day for 40 years, quit last year", progression: "Gets worse every month" },
    correctDiagnosis: "Chronic Obstructive Pulmonary Disease (COPD) - GOLD Stage III",
    correctTreatment: "Long-acting bronchodilators, inhaled corticosteroids, pulmonary rehabilitation, smoking cessation support",
    learningObjectives: ["Classify COPD severity", "Understand spirometry interpretation", "Initiate appropriate therapy"],
    estimatedDuration: 20,
    rating: "4.70"
  },
  {
    name: "Thomas Anderson",
    age: 28,
    gender: "Male",
    specialty: "Pulmonology",
    difficulty: 1,
    chiefComplaint: "Sudden onset of right-sided chest pain and difficulty breathing",
    symptoms: ["pleuritic chest pain", "dyspnea", "tachycardia", "decreased breath sounds on right"],
    medicalHistory: { smoking: "Current smoker", bodyType: "Tall, thin" },
    physicalExam: { vitals: { bp: "120/80", hr: "110", rr: "28", spo2: "94%" }, lungs: "Absent breath sounds on right" },
    labResults: {},
    responses: { onset: "Was just sitting at my desk when it started", painCharacter: "Sharp, worse when I breathe in" },
    correctDiagnosis: "Spontaneous Pneumothorax",
    correctTreatment: "Chest X-ray confirmation, chest tube insertion if large, oxygen therapy",
    learningObjectives: ["Recognize pneumothorax presentation", "Understand risk factors", "Know treatment indications"],
    estimatedDuration: 15,
    rating: "4.65"
  },
  {
    name: "Susan Martinez",
    age: 35,
    gender: "Female",
    specialty: "Pulmonology",
    difficulty: 2,
    chiefComplaint: "Sudden shortness of breath and chest pain after a long flight",
    symptoms: ["dyspnea", "pleuritic chest pain", "tachycardia", "leg swelling"],
    medicalHistory: { oralContraceptives: "Current use", recentTravel: "12-hour flight yesterday" },
    physicalExam: { vitals: { bp: "115/75", hr: "115", rr: "24", spo2: "92%" }, extremities: "Left calf swelling and tenderness" },
    labResults: {},
    responses: { legSymptoms: "My left leg was swollen and painful on the flight", risk: "I take birth control pills" },
    correctDiagnosis: "Pulmonary Embolism with Deep Vein Thrombosis",
    correctTreatment: "CT pulmonary angiography, anticoagulation, consideration of thrombolysis if massive PE",
    learningObjectives: ["Calculate Wells score", "Understand PE risk factors", "Know anticoagulation options"],
    estimatedDuration: 22,
    rating: "4.85"
  },
  {
    name: "Kevin O'Brien",
    age: 8,
    gender: "Male",
    specialty: "Pulmonology",
    difficulty: 1,
    chiefComplaint: "Wheezing and difficulty breathing during soccer practice",
    symptoms: ["wheezing", "cough", "chest tightness", "shortness of breath with exercise"],
    medicalHistory: { allergies: "Pollen, dust mites", eczema: "As an infant", familyHistory: "Mother has asthma" },
    physicalExam: { vitals: { bp: "100/65", hr: "100", rr: "26", spo2: "95%" }, lungs: "Diffuse expiratory wheezes" },
    labResults: {},
    responses: { triggers: "Gets worse during spring and when running", frequency: "Happens every few weeks" },
    correctDiagnosis: "Exercise-Induced Asthma (Allergic Asthma)",
    correctTreatment: "Rescue inhaler before exercise, daily inhaled corticosteroid, allergy management",
    learningObjectives: ["Diagnose pediatric asthma", "Understand asthma classification", "Create asthma action plan"],
    estimatedDuration: 14,
    rating: "4.55"
  },
  {
    name: "Dorothy Wilson",
    age: 70,
    gender: "Female",
    specialty: "Pulmonology",
    difficulty: 3,
    chiefComplaint: "Progressive shortness of breath and dry cough for 2 years",
    symptoms: ["progressive dyspnea", "dry cough", "fatigue", "clubbing"],
    medicalHistory: { occupation: "Worked with asbestos", smoking: "Never" },
    physicalExam: { vitals: { bp: "130/80", hr: "88", rr: "22", spo2: "88%" }, lungs: "Bilateral fine crackles (velcro rales)", fingers: "Digital clubbing" },
    labResults: {},
    responses: { progression: "Slowly getting worse over 2 years", workHistory: "Worked in a shipyard for 30 years" },
    correctDiagnosis: "Idiopathic Pulmonary Fibrosis (IPF)",
    correctTreatment: "High-resolution CT, pulmonary function tests, antifibrotic therapy (pirfenidone or nintedanib), lung transplant evaluation",
    learningObjectives: ["Recognize IPF presentation", "Understand UIP pattern on CT", "Know treatment options"],
    estimatedDuration: 24,
    rating: "4.90"
  },

  // GASTROENTEROLOGY (15 cases)
  {
    name: "Richard Lee",
    age: 42,
    gender: "Male",
    specialty: "Gastroenterology",
    difficulty: 2,
    chiefComplaint: "Severe abdominal pain radiating to the back after heavy drinking",
    symptoms: ["epigastric pain", "nausea", "vomiting", "fever"],
    medicalHistory: { alcohol: "Heavy drinker for 15 years", gallstones: "Previously diagnosed" },
    physicalExam: { vitals: { bp: "100/60", hr: "110", rr: "22", temp: "101.2F" }, abdomen: "Epigastric tenderness, guarding" },
    labResults: {},
    responses: { drinking: "Had about 12 beers yesterday at a party", painTiming: "Started about 6 hours ago and keeps getting worse" },
    correctDiagnosis: "Acute Pancreatitis",
    correctTreatment: "NPO, IV fluids, pain management, monitor for complications",
    learningObjectives: ["Calculate Ranson criteria", "Understand causes of pancreatitis", "Recognize complications"],
    estimatedDuration: 18,
    rating: "4.75"
  },
  {
    name: "Jennifer Taylor",
    age: 55,
    gender: "Female",
    specialty: "Gastroenterology",
    difficulty: 2,
    chiefComplaint: "Blood in stool and unintentional weight loss for 3 months",
    symptoms: ["hematochezia", "weight loss", "change in bowel habits", "fatigue"],
    medicalHistory: { colonoscopy: "Never had one", familyHistory: "Brother had colon cancer at 50" },
    physicalExam: { vitals: { bp: "125/80", hr: "82", rr: "16" }, abdomen: "Mild left lower quadrant fullness", rectal: "Heme positive" },
    labResults: {},
    responses: { bloodDescription: "Bright red blood mixed with stool", bowelChanges: "More constipated than usual, stools are thinner" },
    correctDiagnosis: "Colorectal Cancer (suspected)",
    correctTreatment: "Urgent colonoscopy with biopsy, CT staging if confirmed, oncology referral",
    learningObjectives: ["Recognize red flag symptoms", "Understand screening guidelines", "Know staging workup"],
    estimatedDuration: 20,
    rating: "4.85"
  },
  {
    name: "Anthony Davis",
    age: 38,
    gender: "Male",
    specialty: "Gastroenterology",
    difficulty: 1,
    chiefComplaint: "Heartburn and regurgitation after meals for 6 months",
    symptoms: ["heartburn", "regurgitation", "chest discomfort", "chronic cough"],
    medicalHistory: { obesity: "BMI 32", diet: "Eats late at night", smoking: "Social smoker" },
    physicalExam: { vitals: { bp: "135/88", hr: "78", rr: "16" }, general: "Obese, otherwise unremarkable" },
    labResults: {},
    responses: { symptoms: "Worse when I lie down after eating", triggers: "Spicy food, coffee, alcohol all make it worse" },
    correctDiagnosis: "Gastroesophageal Reflux Disease (GERD)",
    correctTreatment: "PPI therapy, lifestyle modifications, weight loss, dietary changes",
    learningObjectives: ["Diagnose GERD clinically", "Understand lifestyle modifications", "Know when to refer for endoscopy"],
    estimatedDuration: 14,
    rating: "4.50"
  },
  {
    name: "Maria Gonzalez",
    age: 32,
    gender: "Female",
    specialty: "Gastroenterology",
    difficulty: 2,
    chiefComplaint: "Chronic diarrhea, bloating, and abdominal pain for 1 year",
    symptoms: ["chronic diarrhea", "bloating", "abdominal cramping", "fatigue", "weight loss"],
    medicalHistory: { familyHistory: "Autoimmune diseases in family", dermatitis: "Itchy rash on elbows" },
    physicalExam: { vitals: { bp: "110/70", hr: "76", rr: "14" }, abdomen: "Mild diffuse tenderness", skin: "Vesicular rash on extensor surfaces" },
    labResults: {},
    responses: { triggers: "Seems worse after eating bread or pasta", weight: "Lost 15 pounds without trying" },
    correctDiagnosis: "Celiac Disease",
    correctTreatment: "Tissue transglutaminase antibodies, upper endoscopy with biopsy, strict gluten-free diet",
    learningObjectives: ["Recognize celiac presentation", "Understand serological testing", "Know associated conditions"],
    estimatedDuration: 18,
    rating: "4.70"
  },
  {
    name: "Christopher White",
    age: 48,
    gender: "Male",
    specialty: "Gastroenterology",
    difficulty: 3,
    chiefComplaint: "Yellowing of skin and eyes with abdominal pain for 2 weeks",
    symptoms: ["jaundice", "abdominal pain", "dark urine", "pale stools", "pruritus"],
    medicalHistory: { alcohol: "Former heavy drinker", gallstones: "History of" },
    physicalExam: { vitals: { bp: "130/85", hr: "88", rr: "18" }, skin: "Icteric sclera and skin", abdomen: "Tender right upper quadrant, palpable gallbladder" },
    labResults: {},
    responses: { urineChanges: "Urine is dark like tea", itching: "Can't stop scratching, especially at night" },
    correctDiagnosis: "Obstructive Jaundice - Possible Pancreatic Head Mass (Courvoisier sign positive)",
    correctTreatment: "CT abdomen, MRCP, tumor markers (CA 19-9), GI/oncology referral",
    learningObjectives: ["Differentiate obstructive vs hepatocellular jaundice", "Recognize Courvoisier sign", "Understand workup of biliary obstruction"],
    estimatedDuration: 24,
    rating: "4.92"
  },

  // NEUROLOGY (15 cases)
  {
    name: "Barbara Thompson",
    age: 68,
    gender: "Female",
    specialty: "Neurology",
    difficulty: 2,
    chiefComplaint: "Sudden weakness on left side of body and slurred speech 1 hour ago",
    symptoms: ["left hemiparesis", "facial droop", "dysarthria", "confusion"],
    medicalHistory: { atrialFibrillation: "Not on anticoagulation", hypertension: "Poorly controlled", diabetes: "Type 2" },
    physicalExam: { vitals: { bp: "185/105", hr: "92 irregular", rr: "18" }, neuro: "Left facial droop, left arm/leg weakness 2/5, dysarthria" },
    labResults: {},
    responses: { onset: "Was fine this morning, suddenly couldn't move left side", lastNormal: "Was normal at 9am, now it's 10am" },
    correctDiagnosis: "Acute Ischemic Stroke - Right MCA territory",
    correctTreatment: "Activate stroke code, CT head stat, tPA if within window, consider thrombectomy",
    learningObjectives: ["Recognize stroke symptoms", "Calculate NIH Stroke Scale", "Understand time-sensitive treatment"],
    estimatedDuration: 20,
    rating: "4.95"
  },
  {
    name: "William Harris",
    age: 32,
    gender: "Male",
    specialty: "Neurology",
    difficulty: 2,
    chiefComplaint: "Episodes of vision loss and tingling in legs over the past year",
    symptoms: ["optic neuritis", "paresthesias", "fatigue", "urinary urgency"],
    medicalHistory: { none: "Previously healthy" },
    physicalExam: { vitals: { bp: "120/75", hr: "72", rr: "14" }, neuro: "Decreased visual acuity left eye, hyperreflexia in lower extremities, positive Babinski" },
    labResults: {},
    responses: { episodes: "Had blurry vision 6 months ago that got better, now my legs feel tingly", pattern: "Symptoms come and go" },
    correctDiagnosis: "Multiple Sclerosis (Relapsing-Remitting)",
    correctTreatment: "MRI brain and spine with contrast, lumbar puncture, disease-modifying therapy",
    learningObjectives: ["Apply McDonald criteria", "Understand MS presentations", "Know treatment options"],
    estimatedDuration: 22,
    rating: "4.80"
  },
  {
    name: "Nancy Clark",
    age: 75,
    gender: "Female",
    specialty: "Neurology",
    difficulty: 2,
    chiefComplaint: "Progressive memory loss and getting lost in familiar places for 2 years",
    symptoms: ["memory loss", "disorientation", "word-finding difficulty", "personality changes"],
    medicalHistory: { familyHistory: "Mother had dementia" },
    physicalExam: { vitals: { bp: "140/85", hr: "70", rr: "16" }, neuro: "MMSE 18/30, can't recall 3 objects at 5 minutes, difficulty with serial 7s" },
    labResults: {},
    responses: { examples: "Forgot how to get to church, can't remember grandchildren's names", progression: "Getting worse over 2 years" },
    correctDiagnosis: "Alzheimer's Disease (Probable)",
    correctTreatment: "Cognitive testing, MRI brain, rule out reversible causes, cholinesterase inhibitor",
    learningObjectives: ["Perform cognitive assessment", "Differentiate dementia types", "Know available treatments"],
    estimatedDuration: 20,
    rating: "4.65"
  },
  {
    name: "Edward Robinson",
    age: 62,
    gender: "Male",
    specialty: "Neurology",
    difficulty: 2,
    chiefComplaint: "Tremor in hands that started 2 years ago and is getting worse",
    symptoms: ["resting tremor", "bradykinesia", "rigidity", "shuffling gait"],
    medicalHistory: { constipation: "Chronic", sleep: "Acts out dreams at night" },
    physicalExam: { vitals: { bp: "130/80", hr: "68", rr: "14" }, neuro: "Pill-rolling tremor, cogwheel rigidity, masked facies, festinating gait" },
    labResults: {},
    responses: { tremor: "Worse when I'm resting, better when I reach for something", handwriting: "My writing has gotten smaller" },
    correctDiagnosis: "Parkinson's Disease",
    correctTreatment: "Levodopa/carbidopa, physical therapy, occupational therapy, speech therapy",
    learningObjectives: ["Recognize cardinal features", "Differentiate from essential tremor", "Understand treatment approach"],
    estimatedDuration: 18,
    rating: "4.75"
  },
  {
    name: "Carol Lewis",
    age: 45,
    gender: "Female",
    specialty: "Neurology",
    difficulty: 3,
    chiefComplaint: "Severe headache described as 'worst headache of my life'",
    symptoms: ["thunderclap headache", "neck stiffness", "photophobia", "vomiting"],
    medicalHistory: { hypertension: "Untreated", smoking: "Current" },
    physicalExam: { vitals: { bp: "170/100", hr: "95", rr: "18" }, neuro: "Nuchal rigidity, photophobia, no focal deficits" },
    labResults: {},
    responses: { onset: "Came on suddenly while lifting weights", severity: "11 out of 10, nothing like my usual headaches" },
    correctDiagnosis: "Subarachnoid Hemorrhage (ruptured aneurysm)",
    correctTreatment: "CT head stat, if negative LP, CTA/MRA, neurosurgery consultation",
    learningObjectives: ["Recognize SAH presentation", "Understand Hunt-Hess grading", "Know complications (vasospasm, rebleeding)"],
    estimatedDuration: 22,
    rating: "4.95"
  },

  // ENDOCRINOLOGY (12 cases)
  {
    name: "George Walker",
    age: 55,
    gender: "Male",
    specialty: "Endocrinology",
    difficulty: 1,
    chiefComplaint: "Increased thirst and urination, blurry vision for 3 months",
    symptoms: ["polydipsia", "polyuria", "blurred vision", "fatigue", "slow wound healing"],
    medicalHistory: { obesity: "BMI 35", familyHistory: "Both parents diabetic", sedentary: "Office job" },
    physicalExam: { vitals: { bp: "145/92", hr: "82", rr: "16" }, skin: "Acanthosis nigricans on neck", feet: "Decreased sensation to monofilament" },
    labResults: {},
    responses: { thirst: "Drinking gallons of water but still thirsty", urination: "Up 5-6 times at night" },
    correctDiagnosis: "Type 2 Diabetes Mellitus with Diabetic Peripheral Neuropathy",
    correctTreatment: "Metformin, lifestyle modifications, diabetes education, A1c monitoring, eye and foot exams",
    learningObjectives: ["Diagnose diabetes", "Understand screening complications", "Initiate treatment"],
    estimatedDuration: 16,
    rating: "4.55"
  },
  {
    name: "Helen Young",
    age: 28,
    gender: "Female",
    specialty: "Endocrinology",
    difficulty: 2,
    chiefComplaint: "Weight gain, fatigue, and feeling cold all the time for 6 months",
    symptoms: ["weight gain", "fatigue", "cold intolerance", "constipation", "dry skin", "hair loss"],
    medicalHistory: { postpartum: "Had baby 8 months ago" },
    physicalExam: { vitals: { bp: "105/65", hr: "55", rr: "14" }, thyroid: "Mildly enlarged, non-tender", skin: "Dry, cool", reflexes: "Delayed relaxation" },
    labResults: {},
    responses: { energy: "I can barely get through the day", weight: "Gained 20 pounds despite eating less" },
    correctDiagnosis: "Postpartum Thyroiditis - Hypothyroid Phase (likely Hashimoto's)",
    correctTreatment: "TSH, free T4, TPO antibodies, levothyroxine if persistent",
    learningObjectives: ["Recognize hypothyroidism", "Understand postpartum thyroiditis", "Know treatment indications"],
    estimatedDuration: 16,
    rating: "4.70"
  },
  {
    name: "Betty King",
    age: 35,
    gender: "Female",
    specialty: "Endocrinology",
    difficulty: 2,
    chiefComplaint: "Rapid weight loss, palpitations, and anxiety for 2 months",
    symptoms: ["weight loss", "palpitations", "tremor", "heat intolerance", "diarrhea", "insomnia"],
    medicalHistory: { familyHistory: "Sister has thyroid problems" },
    physicalExam: { vitals: { bp: "140/70", hr: "110", rr: "20", temp: "99.2F" }, thyroid: "Diffusely enlarged, non-tender, bruit present", eyes: "Lid lag, proptosis" },
    labResults: {},
    responses: { weight: "Lost 15 pounds eating more than usual", mood: "Feel anxious and can't sit still" },
    correctDiagnosis: "Graves' Disease (Hyperthyroidism)",
    correctTreatment: "TSH, free T4, TSI, beta-blocker, methimazole or PTU, ophthalmology if eye involvement",
    learningObjectives: ["Recognize hyperthyroidism", "Understand Graves' disease features", "Know treatment options"],
    estimatedDuration: 18,
    rating: "4.75"
  },
  {
    name: "Frank Scott",
    age: 48,
    gender: "Male",
    specialty: "Endocrinology",
    difficulty: 3,
    chiefComplaint: "Severe headache, sweating episodes, and very high blood pressure",
    symptoms: ["episodic hypertension", "headache", "diaphoresis", "palpitations", "anxiety"],
    medicalHistory: { hypertension: "Resistant to 3 medications", familyHistory: "Brother had adrenal surgery" },
    physicalExam: { vitals: { bp: "220/120 during episode, 150/90 between", hr: "120 during episode" }, general: "Diaphoretic during episode" },
    labResults: {},
    responses: { episodes: "Come out of nowhere, feel like I'm going to die", frequency: "Several times a week" },
    correctDiagnosis: "Pheochromocytoma",
    correctTreatment: "24-hour urine catecholamines/metanephrines, CT/MRI adrenals, alpha-blockade before surgery",
    learningObjectives: ["Recognize classic triad", "Understand biochemical diagnosis", "Know preoperative management"],
    estimatedDuration: 22,
    rating: "4.90"
  },

  // INFECTIOUS DISEASE (12 cases)
  {
    name: "Alice Turner",
    age: 72,
    gender: "Female",
    specialty: "Infectious Disease",
    difficulty: 2,
    chiefComplaint: "High fever, productive cough, and shortness of breath for 3 days",
    symptoms: ["fever", "productive cough", "dyspnea", "pleuritic chest pain", "fatigue"],
    medicalHistory: { copd: "Moderate", smoking: "40 pack-years", influenzaVaccine: "Not this year" },
    physicalExam: { vitals: { bp: "100/60", hr: "105", rr: "28", temp: "102.8F", spo2: "88%" }, lungs: "Right lower lobe crackles, egophony" },
    labResults: {},
    responses: { sputum: "Thick, rusty-colored sputum", onset: "Started with chills 3 days ago" },
    correctDiagnosis: "Community-Acquired Pneumonia (likely Streptococcus pneumoniae)",
    correctTreatment: "Chest X-ray, blood cultures, sputum culture, empiric antibiotics (fluoroquinolone or beta-lactam + macrolide), oxygen",
    learningObjectives: ["Apply CURB-65 criteria", "Choose appropriate antibiotics", "Know admission criteria"],
    estimatedDuration: 18,
    rating: "4.70"
  },
  {
    name: "Joseph Phillips",
    age: 25,
    gender: "Male",
    specialty: "Infectious Disease",
    difficulty: 2,
    chiefComplaint: "Painful urination and discharge for 5 days",
    symptoms: ["dysuria", "urethral discharge", "urinary frequency", "testicular discomfort"],
    medicalHistory: { sexualHistory: "New partner 2 weeks ago, unprotected sex" },
    physicalExam: { vitals: { bp: "120/75", hr: "72", rr: "14" }, GU: "Purulent urethral discharge, mild epididymal tenderness" },
    labResults: {},
    responses: { discharge: "Yellow-green discharge", partners: "Had unprotected sex with a new partner" },
    correctDiagnosis: "Gonococcal Urethritis with possible Chlamydia co-infection",
    correctTreatment: "Ceftriaxone IM + azithromycin, partner treatment, STI screening, abstinence until treated",
    learningObjectives: ["Recognize STI presentation", "Understand dual therapy rationale", "Know public health implications"],
    estimatedDuration: 14,
    rating: "4.55"
  },
  {
    name: "Ruth Evans",
    age: 82,
    gender: "Female",
    specialty: "Infectious Disease",
    difficulty: 2,
    chiefComplaint: "Confusion and fever in a nursing home resident",
    symptoms: ["altered mental status", "fever", "urinary incontinence", "decreased appetite"],
    medicalHistory: { dementia: "Baseline mild", diabetes: "Type 2", catheter: "Indwelling Foley" },
    physicalExam: { vitals: { bp: "95/55", hr: "110", rr: "22", temp: "101.5F" }, general: "Confused, lethargic", abdomen: "Suprapubic tenderness" },
    labResults: {},
    responses: { baseline: "Usually knows family, now doesn't recognize daughter", urine: "Cloudy, foul-smelling" },
    correctDiagnosis: "Urosepsis from Catheter-Associated UTI",
    correctTreatment: "Blood and urine cultures, IV antibiotics, fluid resuscitation, catheter change",
    learningObjectives: ["Recognize atypical sepsis presentation in elderly", "Understand CAUTI prevention", "Apply sepsis protocols"],
    estimatedDuration: 18,
    rating: "4.80"
  },

  // RHEUMATOLOGY (10 cases)
  {
    name: "Margaret Hill",
    age: 45,
    gender: "Female",
    specialty: "Rheumatology",
    difficulty: 2,
    chiefComplaint: "Joint pain and swelling in hands and feet for 6 months",
    symptoms: ["symmetric polyarthritis", "morning stiffness >1 hour", "fatigue", "low-grade fever"],
    medicalHistory: { familyHistory: "Mother had RA" },
    physicalExam: { vitals: { bp: "125/80", hr: "76", rr: "14" }, hands: "MCP and PIP swelling bilaterally, warmth", feet: "MTP tenderness" },
    labResults: {},
    responses: { morningStiffness: "Takes 2-3 hours before I can make a fist", pattern: "Both hands equally affected" },
    correctDiagnosis: "Rheumatoid Arthritis",
    correctTreatment: "RF, anti-CCP, ESR/CRP, X-rays, methotrexate, folic acid, NSAIDs for symptomatic relief",
    learningObjectives: ["Apply ACR/EULAR criteria", "Understand early aggressive treatment", "Know DMARD options"],
    estimatedDuration: 18,
    rating: "4.75"
  },
  {
    name: "Daniel Adams",
    age: 52,
    gender: "Male",
    specialty: "Rheumatology",
    difficulty: 1,
    chiefComplaint: "Sudden severe pain and swelling in big toe overnight",
    symptoms: ["acute monoarthritis", "exquisite tenderness", "redness", "warmth"],
    medicalHistory: { diet: "Meat and beer lover", obesity: "BMI 32", thiazide: "On hydrochlorothiazide" },
    physicalExam: { vitals: { bp: "145/90", hr: "82", rr: "16" }, rightFoot: "First MTP erythematous, swollen, exquisitely tender, can't bear sheet on it" },
    labResults: {},
    responses: { onset: "Woke up at 2am with terrible pain", triggers: "Had steak and several beers yesterday" },
    correctDiagnosis: "Acute Gouty Arthritis (Podagra)",
    correctTreatment: "NSAIDs or colchicine, consider joint aspiration, uric acid level (after acute attack), lifestyle modifications",
    learningObjectives: ["Recognize classic gout presentation", "Understand precipitating factors", "Know acute vs chronic management"],
    estimatedDuration: 14,
    rating: "4.60"
  },
  {
    name: "Sandra Nelson",
    age: 32,
    gender: "Female",
    specialty: "Rheumatology",
    difficulty: 3,
    chiefComplaint: "Facial rash, joint pain, and fatigue for 3 months",
    symptoms: ["malar rash", "photosensitivity", "arthralgia", "fatigue", "oral ulcers", "hair loss"],
    medicalHistory: { none: "Previously healthy young woman" },
    physicalExam: { vitals: { bp: "130/85", hr: "80", rr: "14" }, skin: "Butterfly rash sparing nasolabial folds", oral: "Painless ulcers on palate", joints: "Synovitis in MCPs" },
    labResults: {},
    responses: { rash: "Gets worse in the sun", other: "Also having some hair fall out and mouth sores" },
    correctDiagnosis: "Systemic Lupus Erythematosus (SLE)",
    correctTreatment: "ANA, anti-dsDNA, complement levels, CBC, UA, hydroxychloroquine, sun protection, rheumatology referral",
    learningObjectives: ["Apply ACR/EULAR SLE criteria", "Understand organ involvement screening", "Know treatment ladder"],
    estimatedDuration: 22,
    rating: "4.85"
  },

  // NEPHROLOGY (8 cases)
  {
    name: "Charles Carter",
    age: 65,
    gender: "Male",
    specialty: "Nephrology",
    difficulty: 2,
    chiefComplaint: "Decreased urination and leg swelling for 1 week",
    symptoms: ["oliguria", "bilateral leg edema", "fatigue", "nausea", "confusion"],
    medicalHistory: { diabetes: "20 years, poorly controlled", hypertension: "15 years", NSAIDs: "Takes ibuprofen daily for arthritis" },
    physicalExam: { vitals: { bp: "165/95", hr: "88", rr: "20" }, extremities: "3+ pitting edema", lungs: "Bibasilar crackles" },
    labResults: {},
    responses: { urineOutput: "Maybe once or twice a day, very little", NSAID: "Take 4-6 ibuprofen daily for my back" },
    correctDiagnosis: "Acute Kidney Injury on Chronic Kidney Disease (likely NSAID-induced + diabetic nephropathy)",
    correctTreatment: "Stop NSAIDs, IV fluids cautiously, monitor electrolytes, nephrology consult, possible dialysis",
    learningObjectives: ["Classify AKI stages", "Identify nephrotoxic medications", "Know dialysis indications"],
    estimatedDuration: 20,
    rating: "4.80"
  },
  {
    name: "Patricia Baker",
    age: 28,
    gender: "Female",
    specialty: "Nephrology",
    difficulty: 2,
    chiefComplaint: "Blood in urine and puffy face for 2 weeks after a sore throat",
    symptoms: ["gross hematuria", "facial edema", "hypertension", "decreased urine output", "tea-colored urine"],
    medicalHistory: { pharyngitis: "3 weeks ago, treated with antibiotics" },
    physicalExam: { vitals: { bp: "155/95", hr: "78", rr: "16" }, face: "Periorbital edema", extremities: "Mild ankle edema" },
    labResults: {},
    responses: { urineColor: "Looks like Coca-Cola", soreThroat: "Had strep throat about 3 weeks ago" },
    correctDiagnosis: "Post-Streptococcal Glomerulonephritis",
    correctTreatment: "Urinalysis, complement levels (low C3), ASO titer, blood pressure control, supportive care",
    learningObjectives: ["Recognize nephritic syndrome", "Understand post-infectious GN", "Know expected recovery"],
    estimatedDuration: 18,
    rating: "4.70"
  },

  // HEMATOLOGY/ONCOLOGY (10 cases)
  {
    name: "Kenneth Mitchell",
    age: 68,
    gender: "Male",
    specialty: "Hematology/Oncology",
    difficulty: 2,
    chiefComplaint: "Fatigue, night sweats, and painless neck lumps for 2 months",
    symptoms: ["fatigue", "night sweats", "lymphadenopathy", "unintentional weight loss", "pruritus"],
    medicalHistory: { none: "Previously healthy" },
    physicalExam: { vitals: { bp: "130/80", hr: "76", rr: "14" }, neck: "Multiple rubbery, non-tender lymph nodes bilaterally", spleen: "Palpable 3cm below costal margin" },
    labResults: {},
    responses: { nightSweats: "Soaking the sheets nightly", weightLoss: "Lost 20 pounds in 2 months without trying" },
    correctDiagnosis: "Hodgkin Lymphoma (suspected based on B symptoms)",
    correctTreatment: "Lymph node biopsy, CT staging, PET scan, oncology referral, ABVD chemotherapy if confirmed",
    learningObjectives: ["Recognize B symptoms", "Understand lymphoma workup", "Know staging system"],
    estimatedDuration: 20,
    rating: "4.85"
  },
  {
    name: "Dorothy Green",
    age: 72,
    gender: "Female",
    specialty: "Hematology/Oncology",
    difficulty: 2,
    chiefComplaint: "Severe fatigue, bone pain, and recurrent infections",
    symptoms: ["fatigue", "bone pain", "recurrent infections", "weakness", "weight loss"],
    medicalHistory: { anemia: "Told I'm anemic but iron doesn't help" },
    physicalExam: { vitals: { bp: "115/70", hr: "95", rr: "16" }, skin: "Pallor", back: "Point tenderness over lumbar spine" },
    labResults: {},
    responses: { infections: "Had pneumonia twice this year", bonePain: "Back hurts all the time, worse with movement" },
    correctDiagnosis: "Multiple Myeloma",
    correctTreatment: "SPEP/UPEP, serum free light chains, bone marrow biopsy, skeletal survey, oncology referral",
    learningObjectives: ["Recognize CRAB criteria", "Understand diagnostic workup", "Know treatment options"],
    estimatedDuration: 22,
    rating: "4.88"
  },
  {
    name: "Timothy Roberts",
    age: 35,
    gender: "Male",
    specialty: "Hematology/Oncology",
    difficulty: 1,
    chiefComplaint: "Easy bruising and nosebleeds for 2 weeks",
    symptoms: ["easy bruising", "epistaxis", "petechiae", "fatigue", "gum bleeding"],
    medicalHistory: { recentIllness: "Had viral infection 3 weeks ago" },
    physicalExam: { vitals: { bp: "120/75", hr: "78", rr: "14" }, skin: "Multiple ecchymoses, scattered petechiae", spleen: "Not palpable" },
    labResults: {},
    responses: { bruising: "Bruises appearing without injury", bleeding: "Gums bleed when I brush teeth" },
    correctDiagnosis: "Immune Thrombocytopenic Purpura (ITP)",
    correctTreatment: "CBC with peripheral smear, rule out secondary causes, observation vs steroids vs IVIG depending on count",
    learningObjectives: ["Recognize ITP presentation", "Understand diagnosis of exclusion", "Know treatment thresholds"],
    estimatedDuration: 16,
    rating: "4.65"
  },

  // EMERGENCY MEDICINE (15 cases)
  {
    name: "Steven Collins",
    age: 45,
    gender: "Male",
    specialty: "Emergency Medicine",
    difficulty: 2,
    chiefComplaint: "Severe abdominal pain that started around the belly button and moved to the right side",
    symptoms: ["RLQ pain", "nausea", "vomiting", "anorexia", "low-grade fever"],
    medicalHistory: { none: "Healthy until today" },
    physicalExam: { vitals: { bp: "130/85", hr: "100", rr: "20", temp: "100.4F" }, abdomen: "RLQ tenderness, rebound, guarding, positive Rovsing sign" },
    labResults: {},
    responses: { painMigration: "Started near belly button, now it's in my lower right side", appetite: "Can't even think about eating" },
    correctDiagnosis: "Acute Appendicitis",
    correctTreatment: "NPO, IV fluids, IV antibiotics, surgical consultation for appendectomy",
    learningObjectives: ["Calculate Alvarado score", "Recognize peritoneal signs", "Know surgical urgency"],
    estimatedDuration: 16,
    rating: "4.75"
  },
  {
    name: "Michelle Stewart",
    age: 32,
    gender: "Female",
    specialty: "Emergency Medicine",
    difficulty: 3,
    chiefComplaint: "Severe allergic reaction after eating shrimp - can't breathe",
    symptoms: ["urticaria", "angioedema", "wheezing", "hypotension", "throat tightness"],
    medicalHistory: { shellfish: "Known allergy", epipen: "Left it at home" },
    physicalExam: { vitals: { bp: "80/50", hr: "130", rr: "32", spo2: "88%" }, skin: "Diffuse urticaria, facial/lip swelling", airway: "Stridor" },
    labResults: {},
    responses: { onset: "Started 10 minutes after eating at a restaurant", breathing: "Getting harder to breathe" },
    correctDiagnosis: "Anaphylaxis",
    correctTreatment: "IM epinephrine STAT, IV access, IV fluids, diphenhydramine, steroids, prepare for intubation if worsening",
    learningObjectives: ["Recognize anaphylaxis", "Know epinephrine dosing", "Understand biphasic reactions"],
    estimatedDuration: 12,
    rating: "4.95"
  },
  {
    name: "Brian Murphy",
    age: 58,
    gender: "Male",
    specialty: "Emergency Medicine",
    difficulty: 2,
    chiefComplaint: "Found unresponsive by family, empty pill bottles nearby",
    symptoms: ["unresponsive", "pinpoint pupils", "respiratory depression", "track marks"],
    medicalHistory: { opioidUse: "Chronic pain, uses opioids", depression: "History of" },
    physicalExam: { vitals: { bp: "90/60", hr: "55", rr: "6", spo2: "82%" }, pupils: "Pinpoint, minimally reactive", arms: "Track marks" },
    labResults: {},
    responses: { scene: "Multiple empty oxycodone bottles found", family: "Has been depressed lately" },
    correctDiagnosis: "Opioid Overdose",
    correctTreatment: "Naloxone, bag-valve mask ventilation, IV access, monitor for re-sedation, psychiatric evaluation when stable",
    learningObjectives: ["Recognize opioid toxidrome", "Know naloxone dosing", "Understand monitoring needs"],
    estimatedDuration: 14,
    rating: "4.85"
  },
  {
    name: "Lisa Sanders",
    age: 28,
    gender: "Female",
    specialty: "Emergency Medicine",
    difficulty: 2,
    chiefComplaint: "Sudden severe right-sided abdominal pain and dizziness",
    symptoms: ["RLQ pain", "vaginal bleeding", "dizziness", "shoulder pain", "syncope episode"],
    medicalHistory: { LMP: "6 weeks ago", sexuallyActive: "Yes", IUD: "Has Mirena" },
    physicalExam: { vitals: { bp: "85/55", hr: "125", rr: "22" }, abdomen: "RLQ tenderness, guarding", pelvic: "Cervical motion tenderness" },
    labResults: {},
    responses: { pregnancy: "Could be pregnant, period is late", pain: "Started suddenly, then felt dizzy and almost passed out" },
    correctDiagnosis: "Ruptured Ectopic Pregnancy",
    correctTreatment: "Large bore IV access, type and crossmatch, STAT urine pregnancy, bedside ultrasound, emergent OB/GYN consultation for surgery",
    learningObjectives: ["Recognize ectopic pregnancy", "Understand risk factors", "Know surgical urgency"],
    estimatedDuration: 16,
    rating: "4.92"
  },

  // PSYCHIATRY (8 cases)
  {
    name: "Amanda Cooper",
    age: 25,
    gender: "Female",
    specialty: "Psychiatry",
    difficulty: 2,
    chiefComplaint: "Feeling hopeless and thinking about ending my life for 2 weeks",
    symptoms: ["depressed mood", "suicidal ideation", "insomnia", "anhedonia", "poor concentration", "guilt"],
    medicalHistory: { depression: "Previous episode 2 years ago", trauma: "History of abuse" },
    physicalExam: { vitals: { bp: "110/70", hr: "68", rr: "14" }, general: "Poor eye contact, psychomotor retardation, tearful" },
    labResults: {},
    responses: { suicidal: "I have pills saved up, thinking about taking them all", support: "I don't feel like I can talk to anyone" },
    correctDiagnosis: "Major Depressive Disorder, Severe, with Suicidal Ideation and Plan",
    correctTreatment: "Immediate safety assessment, consider inpatient hospitalization, remove access to means, SSRI, psychotherapy",
    learningObjectives: ["Conduct suicide risk assessment", "Understand safety planning", "Know hospitalization criteria"],
    estimatedDuration: 22,
    rating: "4.90"
  },
  {
    name: "Jason Reed",
    age: 32,
    gender: "Male",
    specialty: "Psychiatry",
    difficulty: 2,
    chiefComplaint: "Haven't slept in 5 days, spent $50,000 on a business idea",
    symptoms: ["decreased sleep", "grandiosity", "pressured speech", "increased goal-directed activity", "impulsivity", "irritability"],
    medicalHistory: { depression: "History of depressive episodes", bipolar: "Family history" },
    physicalExam: { vitals: { bp: "140/90", hr: "95", rr: "18" }, general: "Hyperverbal, distractible, pressured speech, dressed flamboyantly" },
    labResults: {},
    responses: { sleep: "Don't need sleep, I'm going to be a billionaire", spending: "Maxed out all my credit cards on this amazing opportunity" },
    correctDiagnosis: "Bipolar I Disorder, Manic Episode",
    correctTreatment: "Mood stabilizer (lithium or valproate), consider antipsychotic, rule out substance use, possible hospitalization",
    learningObjectives: ["Recognize mania criteria", "Differentiate from hypomania", "Understand treatment approach"],
    estimatedDuration: 20,
    rating: "4.78"
  },
  {
    name: "Jennifer Wright",
    age: 22,
    gender: "Female",
    specialty: "Psychiatry",
    difficulty: 3,
    chiefComplaint: "The government is monitoring me through my TV and neighbors are spies",
    symptoms: ["paranoid delusions", "auditory hallucinations", "disorganized thinking", "social withdrawal", "flat affect"],
    medicalHistory: { family: "Uncle has schizophrenia", prodrome: "Grades dropped, became isolated over past year" },
    physicalExam: { vitals: { bp: "120/75", hr: "78", rr: "14" }, general: "Poor hygiene, responding to internal stimuli, tangential speech" },
    labResults: {},
    responses: { voices: "They tell me not to trust anyone", beliefs: "I know they're watching me, I can feel it" },
    correctDiagnosis: "Schizophrenia, First Episode",
    correctTreatment: "Second-generation antipsychotic, rule out medical causes, psychoeducation, family support, therapy",
    learningObjectives: ["Recognize positive and negative symptoms", "Understand differential diagnosis", "Know first episode treatment"],
    estimatedDuration: 24,
    rating: "4.88"
  },

  // DERMATOLOGY (8 cases)
  {
    name: "Rachel Morgan",
    age: 35,
    gender: "Female",
    specialty: "Dermatology",
    difficulty: 1,
    chiefComplaint: "Itchy red patches on elbows and knees for years, getting worse",
    symptoms: ["pruritus", "silvery scales", "well-demarcated plaques", "nail pitting"],
    medicalHistory: { familyHistory: "Father has similar rash", stress: "Recent job change" },
    physicalExam: { vitals: { bp: "120/80", hr: "72", rr: "14" }, skin: "Erythematous plaques with silvery scale on elbows, knees, scalp", nails: "Pitting, oil spots" },
    labResults: {},
    responses: { triggers: "Gets worse when stressed", distribution: "Also on my scalp and lower back" },
    correctDiagnosis: "Plaque Psoriasis",
    correctTreatment: "Topical steroids, vitamin D analogues, consider phototherapy or systemic therapy if extensive",
    learningObjectives: ["Recognize psoriasis features", "Understand Auspitz sign", "Know treatment ladder"],
    estimatedDuration: 14,
    rating: "4.55"
  },
  {
    name: "David Foster",
    age: 62,
    gender: "Male",
    specialty: "Dermatology",
    difficulty: 2,
    chiefComplaint: "Changing mole on my back noticed by wife",
    symptoms: ["asymmetric lesion", "irregular borders", "color variation", "growing size"],
    medicalHistory: { sunExposure: "Lifeguard for 20 years", sunburns: "Multiple blistering sunburns as a teen", familyHistory: "Sister had melanoma" },
    physicalExam: { vitals: { bp: "130/82", hr: "70", rr: "14" }, skin: "Asymmetric brown-black lesion 8mm on upper back, irregular borders, color variegation" },
    labResults: {},
    responses: { changes: "Wife says it's gotten darker and bigger", bleeding: "Sometimes catches on shirts and bleeds" },
    correctDiagnosis: "Malignant Melanoma (suspected)",
    correctTreatment: "Excisional biopsy with narrow margins, staging if confirmed, surgical oncology referral",
    learningObjectives: ["Apply ABCDE criteria", "Understand Breslow depth", "Know staging workup"],
    estimatedDuration: 16,
    rating: "4.85"
  },

  // PEDIATRICS (10 cases)
  {
    name: "Emma Johnson",
    age: 4,
    gender: "Female",
    specialty: "Pediatrics",
    difficulty: 1,
    chiefComplaint: "High fever, pulling at right ear, and crying for 2 days",
    symptoms: ["fever", "otalgia", "irritability", "decreased appetite", "sleep disturbance"],
    medicalHistory: { daycare: "Attends daycare", recentURI: "Runny nose last week", vaccines: "Up to date" },
    physicalExam: { vitals: { temp: "102.5F", hr: "120", rr: "24" }, rightTM: "Bulging, erythematous, decreased mobility", leftTM: "Normal" },
    labResults: {},
    responses: { behavior: "Won't let me touch her right ear", feeding: "Not eating or drinking well" },
    correctDiagnosis: "Acute Otitis Media",
    correctTreatment: "High-dose amoxicillin, acetaminophen/ibuprofen for pain, return if not improving in 48-72 hours",
    learningObjectives: ["Recognize AOM findings", "Understand watchful waiting criteria", "Know antibiotic selection"],
    estimatedDuration: 12,
    rating: "4.50"
  },
  {
    name: "Liam Williams",
    age: 2,
    gender: "Male",
    specialty: "Pediatrics",
    difficulty: 2,
    chiefComplaint: "Barking cough and noisy breathing that started tonight",
    symptoms: ["barking cough", "stridor", "hoarseness", "low-grade fever", "rhinorrhea"],
    medicalHistory: { URI: "Runny nose for 3 days", vaccines: "Up to date" },
    physicalExam: { vitals: { temp: "100.8F", hr: "130", rr: "36", spo2: "94%" }, airway: "Inspiratory stridor at rest, barking cough", lungs: "Good air entry bilaterally" },
    labResults: {},
    responses: { cough: "Sounds like a seal barking", timing: "Worse at night, woke up struggling to breathe" },
    correctDiagnosis: "Croup (Laryngotracheobronchitis)",
    correctTreatment: "Dexamethasone, nebulized epinephrine if severe, humidified air, observation",
    learningObjectives: ["Recognize croup presentation", "Apply Westley score", "Know when to hospitalize"],
    estimatedDuration: 14,
    rating: "4.65"
  },
  {
    name: "Olivia Brown",
    age: 6,
    gender: "Female",
    specialty: "Pediatrics",
    difficulty: 2,
    chiefComplaint: "Rash that started on face and spread to body with fever",
    symptoms: ["maculopapular rash", "fever", "cough", "conjunctivitis", "coryza"],
    medicalHistory: { vaccines: "Parents declined MMR vaccine", travel: "Recently returned from international trip" },
    physicalExam: { vitals: { temp: "103.5F", hr: "110", rr: "22" }, eyes: "Bilateral conjunctivitis", mouth: "Koplik spots on buccal mucosa", skin: "Erythematous maculopapular rash starting on face, spreading cephalocaudally" },
    labResults: {},
    responses: { rash: "Started on her face 2 days ago, now on her whole body", vaccination: "We chose not to vaccinate" },
    correctDiagnosis: "Measles (Rubeola)",
    correctTreatment: "Supportive care, vitamin A supplementation, respiratory isolation, report to public health",
    learningObjectives: ["Recognize measles presentation", "Identify Koplik spots", "Understand public health implications"],
    estimatedDuration: 18,
    rating: "4.80"
  },

  // OBSTETRICS/GYNECOLOGY (8 cases)
  {
    name: "Jessica Taylor",
    age: 28,
    gender: "Female",
    specialty: "Obstetrics/Gynecology",
    difficulty: 2,
    chiefComplaint: "Severe pelvic pain and abnormal vaginal discharge for 1 week",
    symptoms: ["pelvic pain", "purulent discharge", "dyspareunia", "fever", "abnormal bleeding"],
    medicalHistory: { sexualHistory: "Multiple partners, inconsistent condom use", STI: "Chlamydia 2 years ago" },
    physicalExam: { vitals: { temp: "101.2F", hr: "95", rr: "16" }, abdomen: "Lower abdominal tenderness", pelvic: "Cervical motion tenderness, purulent discharge" },
    labResults: {},
    responses: { discharge: "Yellow-green and foul-smelling", partners: "New partner 3 weeks ago" },
    correctDiagnosis: "Pelvic Inflammatory Disease (PID)",
    correctTreatment: "Ceftriaxone + doxycycline + metronidazole, partner treatment, STI testing, counseling on safe sex",
    learningObjectives: ["Recognize PID presentation", "Understand Fitz-Hugh-Curtis syndrome", "Know treatment regimens"],
    estimatedDuration: 16,
    rating: "4.70"
  },
  {
    name: "Ashley Martinez",
    age: 32,
    gender: "Female",
    specialty: "Obstetrics/Gynecology",
    difficulty: 2,
    chiefComplaint: "32 weeks pregnant with severe headache and swelling",
    symptoms: ["headache", "edema", "visual changes", "epigastric pain", "hypertension"],
    medicalHistory: { G2P1: "One previous normal pregnancy", prenatal: "No problems until now" },
    physicalExam: { vitals: { bp: "165/105", hr: "88", rr: "18" }, face: "Facial edema", extremities: "3+ pitting edema", reflexes: "Hyperreflexic with clonus" },
    labResults: {},
    responses: { symptoms: "Seeing spots, terrible headache that won't go away", swelling: "Hands and face swollen, gained 10 pounds this week" },
    correctDiagnosis: "Severe Preeclampsia",
    correctTreatment: "Magnesium sulfate for seizure prophylaxis, antihypertensives, steroids for fetal lung maturity, consider delivery",
    learningObjectives: ["Recognize preeclampsia warning signs", "Understand HELLP syndrome", "Know delivery indications"],
    estimatedDuration: 20,
    rating: "4.88"
  },

  // ORTHOPEDICS (8 cases)
  {
    name: "Brandon Davis",
    age: 22,
    gender: "Male",
    specialty: "Orthopedics",
    difficulty: 1,
    chiefComplaint: "Ankle twisted during basketball game, can't bear weight",
    symptoms: ["ankle pain", "swelling", "inability to bear weight", "ecchymosis"],
    medicalHistory: { sports: "College basketball player", previousInjury: "None" },
    physicalExam: { vitals: { bp: "120/75", hr: "80", rr: "14" }, rightAnkle: "Lateral malleolus tenderness, significant swelling, unable to bear weight" },
    labResults: {},
    responses: { mechanism: "Landed on someone's foot and rolled my ankle outward", weight: "Can't put any weight on it" },
    correctDiagnosis: "Lateral Ankle Sprain (Grade II-III) - rule out fibula fracture",
    correctTreatment: "Ottawa ankle rules, X-ray, RICE protocol, possible walking boot, physical therapy",
    learningObjectives: ["Apply Ottawa ankle rules", "Grade ankle sprains", "Know rehabilitation timeline"],
    estimatedDuration: 12,
    rating: "4.45"
  },
  {
    name: "Margaret Wilson",
    age: 78,
    gender: "Female",
    specialty: "Orthopedics",
    difficulty: 2,
    chiefComplaint: "Hip pain after falling at home, can't stand up",
    symptoms: ["hip pain", "inability to bear weight", "leg shortening", "external rotation"],
    medicalHistory: { osteoporosis: "Known, on calcium/vitamin D", falls: "Third fall this year" },
    physicalExam: { vitals: { bp: "150/85", hr: "92", rr: "18" }, rightLeg: "Shortened, externally rotated, unable to move" },
    labResults: {},
    responses: { fall: "Tripped on a rug, fell directly on my hip", pain: "Worst when I try to move my leg" },
    correctDiagnosis: "Right Hip Fracture (likely femoral neck or intertrochanteric)",
    correctTreatment: "X-ray, pain management, orthopedic consultation for surgical repair, VTE prophylaxis, fall risk assessment",
    learningObjectives: ["Recognize hip fracture presentation", "Understand surgical options", "Know perioperative management"],
    estimatedDuration: 16,
    rating: "4.75"
  },

  // UROLOGY (6 cases)
  {
    name: "Robert Johnson",
    age: 65,
    gender: "Male",
    specialty: "Urology",
    difficulty: 1,
    chiefComplaint: "Difficulty urinating and getting up multiple times at night to pee",
    symptoms: ["weak stream", "hesitancy", "nocturia", "incomplete emptying", "frequency"],
    medicalHistory: { none: "Otherwise healthy" },
    physicalExam: { vitals: { bp: "135/85", hr: "72", rr: "14" }, DRE: "Enlarged, smooth, non-tender prostate" },
    labResults: {},
    responses: { nighttime: "Getting up 4-5 times every night", stream: "Takes forever to start and doesn't flow like it used to" },
    correctDiagnosis: "Benign Prostatic Hyperplasia (BPH)",
    correctTreatment: "PSA, urinalysis, AUA symptom score, alpha-blocker (tamsulosin), consider 5-alpha reductase inhibitor",
    learningObjectives: ["Recognize LUTS", "Differentiate BPH from prostate cancer", "Know medical therapy options"],
    estimatedDuration: 14,
    rating: "4.55"
  },
  {
    name: "Andrew Clark",
    age: 35,
    gender: "Male",
    specialty: "Urology",
    difficulty: 2,
    chiefComplaint: "Excruciating flank pain radiating to groin with blood in urine",
    symptoms: ["severe colicky flank pain", "hematuria", "nausea", "vomiting", "restlessness"],
    medicalHistory: { kidneyStones: "One episode 5 years ago", diet: "Low fluid intake, high sodium" },
    physicalExam: { vitals: { bp: "150/95", hr: "100", rr: "20" }, abdomen: "Left CVA tenderness", general: "Unable to find comfortable position" },
    labResults: {},
    responses: { pain: "Comes in waves, worst pain of my life", urine: "Noticed pink/red color" },
    correctDiagnosis: "Ureteral Colic (Kidney Stone)",
    correctTreatment: "Non-contrast CT, pain management (NSAIDs + opioids), alpha-blocker, hydration, strain urine, urology if not passing",
    learningObjectives: ["Recognize renal colic", "Understand stone composition", "Know intervention indications"],
    estimatedDuration: 16,
    rating: "4.72"
  },

  // Additional diverse cases
  {
    name: "Sophia Anderson",
    age: 42,
    gender: "Female",
    specialty: "Internal Medicine",
    difficulty: 2,
    chiefComplaint: "Progressive muscle weakness over 3 months, difficulty climbing stairs",
    symptoms: ["proximal muscle weakness", "fatigue", "heliotrope rash", "Gottron papules"],
    medicalHistory: { none: "Previously healthy" },
    physicalExam: { vitals: { bp: "125/80", hr: "78", rr: "16" }, skin: "Heliotrope rash on eyelids, Gottron papules on knuckles", neuro: "Proximal muscle weakness 4/5" },
    labResults: {},
    responses: { weakness: "Hard to get out of chairs and climb stairs", rash: "Purple discoloration around my eyes appeared first" },
    correctDiagnosis: "Dermatomyositis",
    correctTreatment: "CK levels, EMG, muscle biopsy, malignancy screening, high-dose steroids, steroid-sparing agents",
    learningObjectives: ["Recognize inflammatory myopathy", "Understand paraneoplastic association", "Know treatment approach"],
    estimatedDuration: 20,
    rating: "4.82"
  },
  {
    name: "Marcus Thompson",
    age: 50,
    gender: "Male",
    specialty: "Internal Medicine",
    difficulty: 2,
    chiefComplaint: "Recurrent episodes of severe abdominal pain with dark urine",
    symptoms: ["severe abdominal pain", "dark urine", "neuropathy", "anxiety", "constipation"],
    medicalHistory: { attacks: "Multiple similar episodes over years" },
    physicalExam: { vitals: { bp: "160/100", hr: "110", rr: "18" }, abdomen: "Diffuse tenderness, no peritoneal signs", neuro: "Mild weakness in extremities" },
    labResults: {},
    responses: { urine: "Turns dark red-brown when left out", triggers: "Happens after certain medications and fasting" },
    correctDiagnosis: "Acute Intermittent Porphyria",
    correctTreatment: "IV glucose, hemin infusion, avoid triggers (medications, fasting), pain management, genetic counseling",
    learningObjectives: ["Recognize porphyria presentation", "Understand triggering factors", "Know acute management"],
    estimatedDuration: 22,
    rating: "4.90"
  }
];

async function seedMedicalCases() {
  console.log("Starting to seed medical cases...");
  
  let inserted = 0;
  for (const caseData of medicalCasesData) {
    try {
      await db.insert(medicalCases).values({
        name: caseData.name,
        age: caseData.age,
        gender: caseData.gender,
        specialty: caseData.specialty,
        difficulty: caseData.difficulty,
        chiefComplaint: caseData.chiefComplaint,
        symptoms: caseData.symptoms,
        medicalHistory: caseData.medicalHistory,
        physicalExam: caseData.physicalExam,
        labResults: caseData.labResults || {},
        responses: caseData.responses,
        correctDiagnosis: caseData.correctDiagnosis,
        correctTreatment: caseData.correctTreatment,
        learningObjectives: caseData.learningObjectives,
        estimatedDuration: caseData.estimatedDuration,
        rating: caseData.rating
      });
      inserted++;
      console.log(`Inserted case ${inserted}: ${caseData.name} - ${caseData.correctDiagnosis}`);
    } catch (error) {
      console.log(`Skipped duplicate or error for: ${caseData.name}`);
    }
  }
  
  console.log(`\nSeeding complete! Inserted ${inserted} new medical cases.`);
  process.exit(0);
}

seedMedicalCases();
